#!/bin/bash

API_BASE="org.mpris.MediaPlayer2.Player"
TARGET="org.mpris.MediaPlayer2.vlc"
OBJ_PATH="/org/mpris/MediaPlayer2"
MUSIC_DIR="/home/mitch/Music"

urldecode() {
    PROG="""
import sys, urllib.parse as p
print(p.unquote_plus(sys.stdin.readline().strip()))
"""
    echo "${1}" | python3.6 -c "${PROG}"
}

usage() {
    echo "Usage: cv (np) - Sends a notification containing the current song"
    echo "          (i)nfo - Prints info about the current song to stdout"
    echo "          (p)rev - Plays previous song"
    echo "          (f)ind - Finds song by substring and plays"
    echo "          (s)ample - Queries the Fresher service to play another song"
    exit 0
}

vlc_cmd() {
  case "$#" in
    1) dbus-send --type=method_call --dest=${TARGET} "${OBJ_PATH}" "${API_BASE}.${1}";;
    2) dbus-send --type=method_call --dest=${TARGET} "${OBJ_PATH}" "${API_BASE}.${1}" "${2}";; 
  esac
}

sort_by_length() {
  cat - | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2-
}

play_song() {
  f="$(find "${MUSIC_DIR}" -iname "*${1}*" | sort_by_length | head -n 1)"
    fname=$(basename "$f")
    uri="file://${f}"
    vlc_cmd OpenUri "string:${uri}"

    sleep 0.05 # zzz

    now_playing
}

unset GREP_OPTIONS # guh

playback_status() {
  dbus-send --print-reply "--dest=${TARGET}" "${OBJ_PATH}" \
    org.freedesktop.DBus.Properties.GetAll "string:${API_BASE}" | \
    grep -A 1 PlaybackStatus | awk '/variant/ { print $3 }' | tr -d '"'
}

escape_chars() { 
  echo "${*}" | sed 's/&/&amp;/g'
}

now_playing() {
  f=$(dbus-send --print-reply "--dest=${TARGET}" "${OBJ_PATH}" \
    org.freedesktop.DBus.Properties.GetAll "string:${API_BASE}" | \
    grep -A 1 'xesam' | grep 'file://' | grep -E -o '/[^/][^"]+')

  if [ "${f}x" = "x" ]; then
    return
  fi

  fname=$(urldecode "${f}")
  name=$(basename "${fname%.*}")
  score=$(fresher show --title "${name}")

  if [ "$#" -eq 1 ] && [ "$1" == "notif" ]; then
    msg="$(escape_chars ${name}) [${score}]"
    notify-send "Now playing:" "$msg"
  fi

  if [ "$#" -eq 0 ] || [ "$1" != "title" ]; then
    echo "${name} [${score}]"
  else
    echo "${name}"
  fi
}

case $1 in
  "-h"*) usage;;
  "np") now_playing notif;;
  "i"*) now_playing;;
  "t"*) now_playing title;;
  "n"*) vlc_cmd Next;;
  "p"*) vlc_cmd Previous;;
  "f"*) play_song "$2";;
  "s"*) play_song "$(fresher next)";;
  *) 
    case $(playback_status) in
      "Playing") vlc_cmd Pause;;
      "Paused") vlc_cmd Play;;
    esac;;
esac
